# Generated by Django 2.1.7 on 2019-02-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
    ]
